[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170613033625-fddfe03/master-haskell-20170613033625-fddfe03"
  version = 1
  sha1 = "0a9e91a8c3373a402c5f2c4fc8d9aabb210c03b3"

[build.dist-7-8]
  GHC_VERSION="7.8.4"
  CABAL_VERSION="1.22.4.0"

[build.dist-7-10]
  GHC_VERSION="7.10.2"
  CABAL_VERSION="1.24.0.0"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"

[build.dist-8-0]
  GHC_VERSION="8.0.1"
  CABAL_VERSION="1.24.0.0"

[build.branches-7-8]
  GHC_VERSION="7.8.4"
  CABAL_VERSION="1.22.4.0"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"

[build.branches-8-0]
  GHC_VERSION="8.0.1"
  CABAL_VERSION="1.24.0.0"
